spring:
  application:
    name: store-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      cors:
        allowed-origins: "*"
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
        allowed-headers:
          - "*"
      routes:
        - id: store-auth
          uri: lb://store-auth
          predicates:
            - Path=/auth/**
          # filters:
          #   - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: store-account
          uri: lb://store-account
          predicates:
            - Path=/accounts/**
          # filters:
          #   - RewritePath=/accounts/(?<segment>.*), /$\{segment}

        - id: store-aluno
          uri: lb://store-aluno
          predicates:
            - Path=/aluno/**
          # filters:
          #   - RewritePath=/aluno/(?<segment>.*), /$\{segment}

        # - id: recomendacao
        #   uri: https://recomendacao.api.projetohorizontes.com
        #   predicates:
        #     - Path=/recomendacao/**
        #   filters:
        #     - RewritePath=/recomendacao/(?<segment>.*), /$\{segment}


        - id: store-instituicao
          uri: lb://store-instituicao
          predicates:
            - Path=/instituicao/**

        # - id: store-recomendacao
        #   uri: lb://store-recomendacao
        #   predicates:
        #     - Path=/recomendacao/**


management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ '*' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://10.100.110.190:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      GET /instituicao/**,
      GET /instituicao**,
      GET /instituicao,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      ANY /auth/prometheus,
      ANY /recomendacao/**,
      GET /aluno/**,
      POST /aluno/**,
      ANY /auth/swagger-ui.html,
      ANY /accounts/swagger-ui.html,
      ANY /aluno/swagger-ui.html
  
