spring:
  application:
    name: store-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders:
            - Content-Type
            - Authorization
            - X-Requested-With
            - Accept
            - Origin
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: store-auth
          uri: lb://store-auth
          predicates:
            - Path=/auth/**

        - id: store-account
          uri: lb://store-account
          predicates:
            - Path=/accounts/**

        - id: store-aluno
          uri: lb://store-aluno
          predicates:
            - Path=/aluno/**
          

        - id: store-instituicao
          uri: lb://store-instituicao
          predicates:
            - Path=/instituicao/**

        - id: store-recomendacao
          uri: lb://store-recomendacao
          predicates:
            - Path=/recomendacao/**


management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ '*' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      ANY /auth/prometheus,
      ANY /aluno/**,
      GET /instituicao/**,  
      ANY /auth/swagger-ui.html,
      ANY /accounts/swagger-ui.html,
      ANY /aluno/swagger-ui.html,
      ANY /instituicao/swagger-ui.html,
      ANY /recomendacao/**
